use cpal::traits::{DeviceTrait, StreamTrait};
use cpal::{Device, FromSample, Sample, SampleFormat, SizedSample, Stream, StreamConfig};
use derive_getters::Getters;
use mockall::automock;
use ringbuf::consumer::Consumer;
use ringbuf::producer::Producer;
use ringbuf::traits::Split;
use ringbuf::{HeapCons, HeapProd, HeapRb};
use tracing::error;

/// A thin wrapper around a CPAL [`Stream`] that allows it to be started
/// through a trait object, enabling mocking in tests.
pub trait PlayableStream: Send {
    /// Starts playback/capture on the underlying stream.
    ///
    /// # Panics
    ///
    /// Panics if the underlying CPAL stream returns an error when playing.
    fn play(&self);
}

impl PlayableStream for Stream {
    /// Starts the CPAL stream and unwraps any error.
    fn play(&self) {
        StreamTrait::play(self).unwrap();
    }
}

/// Abstraction over the audio I/O handler used by [`AudioService`].
///
/// Using the [`MockAudioHandlerTrait`] generated by `mockall` allows the audio
/// pipeline to be tested without real hardware.
///
/// [`AudioService`]: crate::services::audio_service::AudioService
#[automock]
pub trait AudioHandlerTrait: Send + Sync {
    /// Builds and returns a started-ready input stream that pushes captured
    /// samples into `prod` (producer).
    ///
    /// # Arguments
    ///
    /// * `prod` - The ring-buffer producer that receives raw `f32` audio samples.
    fn build_input_stream(&self, prod: HeapProd<f32>) -> Box<dyn PlayableStream>;

    /// Builds and returns a started-ready output stream that drains samples
    /// from `cons` (consumer) and sends them to the output device.
    ///
    /// Slots in the output buffer that have no corresponding sample are
    /// filled with silence (`0.0`).
    ///
    /// # Arguments
    ///
    /// * `cons` - The ring-buffer consumer supplying processed `f32` samples.
    fn build_output_stream(&self, cons: HeapCons<f32>) -> Box<dyn PlayableStream>;

    /// Returns a reference to the CPAL input device used by this handler.
    fn input_device(&self) -> &Device;

    /// Returns a reference to the CPAL output device used by this handler.
    fn output_device(&self) -> &Device;

    /// Returns the [`StreamConfig`] used for the input stream.
    fn input_config(&self) -> &StreamConfig;

    /// Returns the [`StreamConfig`] used for the output stream.
    fn output_config(&self) -> &StreamConfig;

    /// Returns the configured input sample rate in Hz.
    fn input_sample_rate(&self) -> u32;

    /// Returns the configured output sample rate in Hz.
    fn output_sample_rate(&self) -> u32;
}

/// Concrete implementation of [`AudioHandlerTrait`] backed by real CPAL devices.
///
/// `AudioHandler` owns the input device, output device, and stream configuration
/// required to build CPAL streams. It is cheaply cloneable so that it can be
/// shared across threads via [`Arc`].
///
/// [`Arc`]: std::sync::Arc
#[derive(Clone, Getters)]
pub struct AudioHandler {
    input_device: Device,
    output_device: Device,
    input_config: StreamConfig,
    output_config: StreamConfig,
    input_sample_rate: u32,
    output_sample_rate: u32,
    input_sample_format: SampleFormat,
    output_sample_format: SampleFormat,
}

impl AudioHandler {
    /// Creates a new `AudioHandler` with the given CPAL devices and stream config.
    ///
    /// Automatically detects the input and output sample formats supported by
    /// the devices. Falls back to the device defaults or `F32` if detection fails.
    ///
    /// # Arguments
    ///
    /// * `input_device` - The CPAL device used to capture audio.
    /// * `output_device` - The CPAL device used to play back audio.
    /// * `input_config` - The [`StreamConfig`] used for the input stream.
    /// * `output_config` - The [`StreamConfig`] used for the output stream.
    pub fn new(
        input_device: Device,
        output_device: Device,
        input_config: StreamConfig,
        output_config: StreamConfig,
    ) -> Self {
        let input_sample_rate = input_config.sample_rate;
        let output_sample_rate = output_config.sample_rate;

        let input_sample_format = Self::detect_input_sample_format(&input_device, &input_config)
            .or_else(|| {
                input_device
                    .default_input_config()
                    .ok()
                    .map(|c| c.sample_format())
            })
            .unwrap_or(SampleFormat::F32);

        let output_sample_format =
            Self::detect_output_sample_format(&output_device, &output_config)
                .or_else(|| {
                    output_device
                        .default_output_config()
                        .ok()
                        .map(|c| c.sample_format())
                })
                .unwrap_or(SampleFormat::F32);

        Self {
            input_device,
            output_device,
            input_config,
            output_config,
            input_sample_rate,
            output_sample_rate,
            input_sample_format,
            output_sample_format,
        }
    }

    /// Attempts to detect the sample format supported by the input device
    /// for the given stream configuration.
    ///
    /// Returns `None` if the device does not report supported formats.
    ///
    /// # Preference Behavior
    ///
    /// This function explicitly prefers [`SampleFormat::F32`] when available for the target
    /// configuration. This avoids hardware format conversion issues that are known to cause
    /// audio crackling on certain hosts (such as WASAPI) when relying on CPAL's internal
    /// fallback conversion.
    ///
    /// # Arguments
    ///
    /// * `device` - The CPAL input device to check.
    /// * `config` - The target stream configuration.
    fn detect_input_sample_format(device: &Device, config: &StreamConfig) -> Option<SampleFormat> {
        let ranges: Vec<_> = device.supported_input_configs().ok()?.collect();
        // Prefer F32 when available at the target config to avoid format conversion issues
        // that can cause crackling on WASAPI. The old code always used hardcoded f32 callbacks
        // and relied on CPAL's internal format conversion.
        for range in &ranges {
            if range.sample_format() == SampleFormat::F32
                && range.channels() == config.channels
                && range.min_sample_rate() <= config.sample_rate
                && range.max_sample_rate() >= config.sample_rate
            {
                return Some(SampleFormat::F32);
            }
        }
        ranges
            .into_iter()
            .find(|range| {
                range.channels() == config.channels
                    && range.min_sample_rate() <= config.sample_rate
                    && range.max_sample_rate() >= config.sample_rate
            })
            .map(|range| range.sample_format())
    }

    /// Attempts to detect the sample format supported by the output device
    /// for the given stream configuration.
    ///
    /// Returns `None` if the device does not report supported formats.
    ///
    /// # Preference Behavior
    ///
    /// This function explicitly prefers [`SampleFormat::F32`] when available for the target
    /// configuration. This avoids hardware format conversion issues that are known to cause
    /// audio crackling on certain hosts (such as WASAPI) when relying on CPAL's internal
    /// fallback conversion.
    ///
    ///
    /// # Arguments
    ///
    /// * `device` - The CPAL output device to check.
    /// * `config` - The target stream configuration.
    fn detect_output_sample_format(device: &Device, config: &StreamConfig) -> Option<SampleFormat> {
        let ranges: Vec<_> = device.supported_output_configs().ok()?.collect();
        // and relied on CPAL's internal format conversion.
        for range in &ranges {
            if range.sample_format() == SampleFormat::F32
                && range.channels() == config.channels
                && range.min_sample_rate() <= config.sample_rate
                && range.max_sample_rate() >= config.sample_rate
            {
                return Some(SampleFormat::F32);
            }
        }
        ranges
            .into_iter()
            .find(|range| {
                range.channels() == config.channels
                    && range.min_sample_rate() <= config.sample_rate
                    && range.max_sample_rate() >= config.sample_rate
            })
            .map(|range| range.sample_format())
    }

    /// Builds a typed CPAL input stream for the given sample type `T`.
    ///
    /// Captured samples are converted to `f32` and pushed into the ring buffer.
    ///
    /// # Arguments
    ///
    /// * `producer` - The ring-buffer producer receiving the converted samples.
    ///
    /// # Type Parameters
    ///
    /// * `T` - The sample type provided by the CPAL backend.
    fn build_typed_input_stream<T>(&self, mut producer: HeapProd<f32>) -> Stream
    where
        T: Sample + SizedSample,
        f32: FromSample<T>,
    {
        self.input_device
            .build_input_stream(
                &self.input_config,
                move |data: &[T], _| {
                    for &s in data {
                        let _ = producer.try_push(f32::from_sample(s));
                    }
                },
                move |err| error!("Input error: {:?}", err),
                None,
            )
            .unwrap()
    }

    /// Builds a typed CPAL output stream for the given sample type `T`.
    ///
    /// Samples are popped from the ring buffer and converted into the output
    /// sample type. Missing samples are replaced with silence (`0.0`).
    ///
    /// # Arguments
    ///
    /// * `consumer` - The ring-buffer consumer supplying source samples.
    ///
    /// # Type Parameters
    ///
    /// * `T` - The sample type expected by the CPAL backend.
    fn build_typed_output_stream<T>(&self, mut consumer: HeapCons<f32>) -> Stream
    where
        T: Sample + SizedSample + FromSample<f32>,
    {
        self.output_device
            .build_output_stream(
                &self.output_config,
                move |out: &mut [T], _| {
                    for o in out.iter_mut() {
                        *o = T::from_sample(consumer.try_pop().unwrap_or(0.0));
                    }
                },
                move |err| eprintln!("Output error: {:?}", err),
                None,
            )
            .unwrap()
    }

    /// Creates a lock-free ring buffer of `f32` samples with the given capacity.
    ///
    /// Returns a `(producer, consumer)` pair that can be moved into separate
    /// threads for wait-free, single-producer/single-consumer audio transfer.
    ///
    /// # Arguments
    ///
    /// * `size` - The number of `f32` samples the ring buffer can hold.
    ///
    /// # Returns
    ///
    /// A tuple containing the [`HeapProd<f32>`] and [`HeapCons<f32>`].
    pub fn create_ringbuffer(size: usize) -> (HeapProd<f32>, HeapCons<f32>) {
        let rb = HeapRb::<f32>::new(size);
        rb.split()
    }

    /// Replaces the current output device.
    ///
    /// # Arguments
    ///
    /// * `output_device` - The new CPAL output device.
    pub fn set_output_device(&mut self, output_device: Device) {
        self.output_device = output_device;
    }

    /// Replaces the current input device.
    ///
    /// # Arguments
    ///
    /// * `input_device` - The new CPAL input device.
    pub fn set_input_device(&mut self, input_device: Device) {
        self.input_device = input_device;
    }
}

impl AudioHandlerTrait for AudioHandler {
    /// Builds a CPAL input stream that forwards every captured sample into the
    /// provided ring-buffer producer.
    ///
    /// Samples that cannot be pushed (i.e. the ring buffer is full) are silently
    /// dropped. Input errors are logged.
    ///
    /// # Arguments
    ///
    /// * `producer` - The ring-buffer producer target.
    ///
    /// # Returns
    ///
    /// A boxed trait object implementing [`PlayableStream`].
    ///
    /// # Panics
    ///
    /// Panics if CPAL fails to build the input stream.
    fn build_input_stream(&self, producer: HeapProd<f32>) -> Box<dyn PlayableStream> {
        let stream = match self.input_sample_format {
            SampleFormat::I8 => self.build_typed_input_stream::<i8>(producer),
            SampleFormat::I16 => self.build_typed_input_stream::<i16>(producer),
            SampleFormat::I32 => self.build_typed_input_stream::<i32>(producer),
            SampleFormat::I64 => self.build_typed_input_stream::<i64>(producer),
            SampleFormat::U8 => self.build_typed_input_stream::<u8>(producer),
            SampleFormat::U16 => self.build_typed_input_stream::<u16>(producer),
            SampleFormat::U32 => self.build_typed_input_stream::<u32>(producer),
            SampleFormat::U64 => self.build_typed_input_stream::<u64>(producer),
            SampleFormat::F32 => self.build_typed_input_stream::<f32>(producer),
            SampleFormat::F64 => self.build_typed_input_stream::<f64>(producer),
            _ => panic!(
                "Unsupported input sample format for stream building: {:?}",
                self.input_sample_format
            ),
        };
        Box::new(stream)
    }

    /// Builds a CPAL output stream that drains samples from the provided
    /// ring-buffer consumer into the hardware output buffer.
    ///
    /// Any output slot that has no corresponding sample is filled with `0.0`
    /// (silence). Output errors are printed to stderr.
    ///
    /// # Arguments
    ///
    /// * `consumer` - The ring-buffer consumer source.
    ///
    /// # Returns
    ///
    /// A boxed trait object implementing [`PlayableStream`].
    ///
    /// # Panics
    ///
    /// Panics if CPAL fails to build the output stream.
    fn build_output_stream(&self, consumer: HeapCons<f32>) -> Box<dyn PlayableStream> {
        let stream = match self.output_sample_format {
            SampleFormat::I8 => self.build_typed_output_stream::<i8>(consumer),
            SampleFormat::I16 => self.build_typed_output_stream::<i16>(consumer),
            SampleFormat::I32 => self.build_typed_output_stream::<i32>(consumer),
            SampleFormat::I64 => self.build_typed_output_stream::<i64>(consumer),
            SampleFormat::U8 => self.build_typed_output_stream::<u8>(consumer),
            SampleFormat::U16 => self.build_typed_output_stream::<u16>(consumer),
            SampleFormat::U32 => self.build_typed_output_stream::<u32>(consumer),
            SampleFormat::U64 => self.build_typed_output_stream::<u64>(consumer),
            SampleFormat::F32 => self.build_typed_output_stream::<f32>(consumer),
            SampleFormat::F64 => self.build_typed_output_stream::<f64>(consumer),
            _ => panic!(
                "Unsupported output sample format for stream building: {:?}",
                self.output_sample_format
            ),
        };
        Box::new(stream)
    }

    /// Returns a reference to the CPAL input device.
    ///
    /// # Returns
    ///
    /// Reference to the internal input [`Device`].
    fn input_device(&self) -> &Device {
        &self.input_device
    }

    /// Returns a reference to the CPAL output device.
    ///
    /// # Returns
    ///
    /// Reference to the internal output [`Device`].
    fn output_device(&self) -> &Device {
        &self.output_device
    }

    /// Returns the input stream configuration.
    ///
    /// # Returns
    ///
    /// Reference to the input [`StreamConfig`].
    fn input_config(&self) -> &StreamConfig {
        &self.input_config
    }

    /// Returns the output stream configuration.
    ///
    /// # Returns
    ///
    /// Reference to the output [`StreamConfig`].
    fn output_config(&self) -> &StreamConfig {
        &self.output_config
    }

    /// Returns the configured input sample rate in Hz.
    ///
    /// # Returns
    ///
    /// The input sample rate value as a `u32`.
    fn input_sample_rate(&self) -> u32 {
        self.input_sample_rate
    }

    /// Returns the configured output sample rate in Hz.
    ///
    /// # Returns
    ///
    /// The output sample rate value as a `u32`.
    fn output_sample_rate(&self) -> u32 {
        self.output_sample_rate
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use cpal::traits::HostTrait;

    fn create_null_device() -> Device {
        let host = cpal::default_host();
        host.default_input_device().unwrap_or_else(|| {
            let mut devices = host.devices().unwrap();
            devices.next().unwrap_or_else(|| {
                panic!(
                    "No hardware audio device available to complete structural test evaluation."
                );
            })
        })
    }

    fn create_dummy_configs() -> (StreamConfig, StreamConfig) {
        let input = StreamConfig {
            channels: 1,
            sample_rate: 44100,
            buffer_size: cpal::BufferSize::Default,
        };
        let output = StreamConfig {
            channels: 2,
            sample_rate: 48000,
            buffer_size: cpal::BufferSize::Default,
        };
        (input, output)
    }

    #[cfg(test)]
    mod success_path {
        use super::*;

        #[test]
        fn test_input_callback_pushes_samples() {
            let (mut prod, mut cons) = AudioHandler::create_ringbuffer(16);

            let input_data = vec![0.1, 0.2, 0.3, 0.4];
            {
                for &s in &input_data {
                    let _ = prod.try_push(s);
                }
            }

            for expected in input_data {
                assert_eq!(cons.try_pop(), Some(expected));
            }
        }

        #[test]
        fn test_output_callback_reads_samples() {
            let (mut prod, mut cons) = AudioHandler::create_ringbuffer(16);
            prod.try_push(10.0).unwrap();
            prod.try_push(20.0).unwrap();
            prod.try_push(30.0).unwrap();

            let mut out = [0.0f32; 5];
            {
                for o in out.iter_mut() {
                    *o = cons.try_pop().unwrap_or(0.0);
                }
            }

            assert_eq!(out, [10.0, 20.0, 30.0, 0.0, 0.0]);
        }

        #[test]
        fn test_getters_and_setters_mutability() {
            let dev_input = create_null_device();
            let dev_output = create_null_device();
            let (config_in, config_out) = create_dummy_configs();

            let mut handler = AudioHandler::new(
                dev_input.clone(),
                dev_output.clone(),
                config_in.clone(),
                config_out.clone(),
            );

            assert_eq!(handler.input_sample_rate, 44100);
            assert_eq!(handler.output_sample_rate, 48000);
            assert_eq!(handler.input_config().channels, 1);
            assert_eq!(handler.output_config().channels, 2);

            let new_dev_input = create_null_device();
            let new_dev_output = create_null_device();

            handler.set_input_device(new_dev_input);
            handler.set_output_device(new_dev_output);
        }
    }

    #[cfg(test)]
    mod failure_path {
        use super::*;

        #[test]
        fn test_input_callback_drops_when_full() {
            let (mut prod, mut cons) = AudioHandler::create_ringbuffer(3);

            let input_data = vec![1.0, 2.0, 3.0, 4.0, 5.0];

            for &s in &input_data {
                let _ = prod.try_push(s);
            }

            assert_eq!(cons.try_pop(), Some(1.0));
            assert_eq!(cons.try_pop(), Some(2.0));
            assert_eq!(cons.try_pop(), Some(3.0));
            assert_eq!(cons.try_pop(), None);
        }

        #[test]
        fn test_output_callback_zero_fills_when_empty() {
            let (_prod, mut cons) = AudioHandler::create_ringbuffer(8);

            let mut out = [1.0f32; 4];

            {
                for o in out.iter_mut() {
                    *o = cons.try_pop().unwrap_or(0.0);
                }
            }

            assert_eq!(out, [0.0, 0.0, 0.0, 0.0]);
        }
    }
}
