/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.5.0
 * Generated at: 2026-05-07T09:21:25.214572700+00:00
 * Generator: none
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import {invoke} from '@tauri-apps/api/core';
import * as types from './types';

export async function setChannelId(params: types.SetChannelIdParams): Promise<void> {
  return invoke('set_channel_id', params);
}



export async function getChannelId(): Promise<number> {
  return invoke('get_channel_id');
}


export async function addChannel(params: types.AddChannelParams): Promise<void> {
  return invoke('add_channel', params);
}



export async function getAllChannels(): Promise<types.ChannelDto[]> {
  return invoke('get_all_channels');
}


export async function removeChannel(params: types.RemoveChannelParams): Promise<void> {
  return invoke('remove_channel', params);
}



export async function startLoopback(): Promise<void> {
  return invoke('start_loopback');
}



export async function getInputDeviceList(): Promise<types.AudioDeviceDto[]> {
  return invoke('get_input_device_list');
}



export async function getOutputDeviceList(): Promise<types.AudioDeviceDto[]> {
  return invoke('get_output_device_list');
}


export async function setInputDevice(params: types.SetInputDeviceParams): Promise<void> {
  return invoke('set_input_device', params);
}


export async function setOutputDevice(params: types.SetOutputDeviceParams): Promise<void> {
  return invoke('set_output_device', params);
}



export async function getBufferSizeFrames(): Promise<number> {
  return invoke('get_buffer_size_frames');
}


export async function setBufferSizeFrames(params: types.SetBufferSizeFramesParams): Promise<void> {
  return invoke('set_buffer_size_frames', params);
}



export async function getAmpConfig(): Promise<types.AmpConfigDto> {
  return invoke('get_amp_config');
}


export async function toggleOnOff(params: types.ToggleOnOffParams): Promise<void> {
  return invoke('toggle_on_off', params);
}


export async function setGain(params: types.SetGainParams): Promise<void> {
  return invoke('set_gain', params);
}


export async function setMasterVolume(params: types.SetMasterVolumeParams): Promise<void> {
  return invoke('set_master_volume', params);
}


export async function setToneStack(params: types.SetToneStackParams): Promise<void> {
  return invoke('set_tone_stack', params);
}


export async function setBass(params: types.SetBassParams): Promise<void> {
  return invoke('set_bass', params);
}


export async function setMiddle(params: types.SetMiddleParams): Promise<void> {
  return invoke('set_middle', params);
}


export async function setTreble(params: types.SetTrebleParams): Promise<void> {
  return invoke('set_treble', params);
}


export async function setVolume(params: types.SetVolumeParams): Promise<void> {
  return invoke('set_volume', params);
}


export async function addEffect(params: types.AddEffectParams): Promise<void> {
  return invoke('add_effect', params);
}


export async function removeEffect(params: types.RemoveEffectParams): Promise<void> {
  return invoke('remove_effect', params);
}


export async function applyEffectOrderChange(params: types.ApplyEffectOrderChangeParams): Promise<void> {
  return invoke('apply_effect_order_change', params);
}


export async function toggleEffect(params: types.ToggleEffectParams): Promise<boolean> {
  return invoke('toggle_effect', params);
}


export async function setHcDistortionThreshold(params: types.SetHcDistortionThresholdParams): Promise<void> {
  return invoke('set_hc_distortion_threshold', params);
}


export async function setHcDistortionLevel(params: types.SetHcDistortionLevelParams): Promise<void> {
  return invoke('set_hc_distortion_level', params);
}


export async function setDelayLevel(params: types.SetDelayLevelParams): Promise<void> {
  return invoke('set_delay_level', params);
}


export async function setDelayDelayTime(params: types.SetDelayDelayTimeParams): Promise<void> {
  return invoke('set_delay_delay_time', params);
}



export async function testGainLatency(): Promise<void> {
  return invoke('test_gain_latency');
}



export async function measureAllDspCpuTimings(): Promise<types.ExecutionTimingDto[]> {
  return invoke('measure_all_dsp_cpu_timings');
}



export async function measureAllDspAlgorithmicLatency(): Promise<types.AlgorithmicLatencyDto[]> {
  return invoke('measure_all_dsp_algorithmic_latency');
}



export async function measureBufferLatency(): Promise<types.BufferLatencyDto> {
  return invoke('measure_buffer_latency');
}



export async function measureRoundTripLatency(): Promise<types.RoundTripLatencyDto> {
  return invoke('measure_round_trip_latency');
}


