/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.5.0
 * Generated at: 2026-05-11T13:14:10.943470900+00:00
 * Generator: none
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

/**
 * Event Listeners
 * Type-safe event listener helpers for Tauri events
 */
import {listen, type UnlistenFn} from '@tauri-apps/api/event';
import * as types from './types';

/**
 * Listen for 'channel-added' events
 * @param handler - Callback function to handle the event
 * @returns Promise that resolves to an unlisten function
 */
export async function onChannelAdded(
  handler: (payload: types.ChannelDto) => void
): Promise<UnlistenFn> {
  return listen<types.ChannelDto>('channel-added', (event) => {
    handler(event.payload);
  });
}


