/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.5.0
 * Generated at: 2026-04-29T14:54:19.050231100+00:00
 * Generator: none
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */



export interface ChannelDto {
  id: number;
  name: string;
  gain: number;
  tone_stack: ToneStackDto;
  volume: number;
  effect_chain: EffectDto[];
}

export interface EffectDto {
  id: number;
  name: string;
  is_active: boolean;
}

export interface AmpConfigDto {
  master_volume: number;
  is_active: boolean;
  channels: ChannelDto[];
  current_channel: number;
}

export interface ToneStackDto {
  bass: number;
  middle: number;
  treble: number;
}

export interface AudioDeviceDto {
  id: string;
  name: string;
  sample_rate: number;
}



export interface SetInputDeviceParams {
  deviceId: string;
  [key: string]: unknown;
}


export interface SetOutputDeviceParams {
  deviceId: string;
  [key: string]: unknown;
}




export interface ToggleOnOffParams {
  isOn: boolean;
  [key: string]: unknown;
}


export interface SetGainParams {
  gain: number;
  [key: string]: unknown;
}


export interface SetMasterVolumeParams {
  masterVolume: number;
  [key: string]: unknown;
}


export interface SetToneStackParams {
  toneStack: ToneStackDto;
  [key: string]: unknown;
}


export interface SetBassParams {
  bass: number;
  [key: string]: unknown;
}


export interface SetMiddleParams {
  middle: number;
  [key: string]: unknown;
}


export interface SetTrebleParams {
  treble: number;
  [key: string]: unknown;
}


export interface SetVolumeParams {
  volume: number;
  [key: string]: unknown;
}


export interface SetChannelIdParams {
  channelId: number;
  [key: string]: unknown;
}



export interface AddChannelParams {
  channelName: string;
  [key: string]: unknown;
}



export interface RemoveChannelParams {
  channelId: number;
  [key: string]: unknown;
}


