/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.5.0
 * Generated at: 2026-05-07T09:21:25.213837700+00:00
 * Generator: none
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */



export interface BufferLatencyDto {
  input_buffer_latency_ms: number;
  output_buffer_latency_ms: number;
  total_buffer_latency_ms: number;
}

export interface AudioDeviceDto {
  id: string;
  name: string;
  sample_rate: number;
}

export interface RoundTripLatencyDto {
  latency_ms: number;
  is_valid: boolean;
  error?: string | null;
}


export type EffectDto =
| { kind: "HCDistortion"; data: HcDistortionDto }
| { kind: "Delay"; data: DelayDto }
;

export interface AmpConfigDto {
  master_volume: number;
  is_active: boolean;
  channels: ChannelDto[];
  current_channel: number;
}

export interface ToneStackDto {
  bass: number;
  middle: number;
  treble: number;
}

export interface ExecutionTimingDto {
  processor_name: string;
  execution_us_per_sample: number;
}

export interface AlgorithmicLatencyDto {
  processor_name: string;
  latency_samples: number;
  latency_ms: number;
}

export interface ChannelDto {
  id: number;
  name: string;
  gain: number;
  tone_stack: ToneStackDto;
  volume: number;
  effect_chain: EffectDto[];
}

export interface SetChannelIdParams {
  channelId: number;
  [key: string]: unknown;
}



export interface AddChannelParams {
  channelName: string;
  [key: string]: unknown;
}



export interface RemoveChannelParams {
  channelId: number;
  [key: string]: unknown;
}





export interface SetInputDeviceParams {
  deviceId: string;
  [key: string]: unknown;
}


export interface SetOutputDeviceParams {
  deviceId: string;
  [key: string]: unknown;
}



export interface SetBufferSizeFramesParams {
  frames: number;
  [key: string]: unknown;
}



export interface ToggleOnOffParams {
  isOn: boolean;
  [key: string]: unknown;
}


export interface SetGainParams {
  gain: number;
  [key: string]: unknown;
}


export interface SetMasterVolumeParams {
  masterVolume: number;
  [key: string]: unknown;
}


export interface SetToneStackParams {
  toneStack: ToneStackDto;
  [key: string]: unknown;
}


export interface SetBassParams {
  bass: number;
  [key: string]: unknown;
}


export interface SetMiddleParams {
  middle: number;
  [key: string]: unknown;
}


export interface SetTrebleParams {
  treble: number;
  [key: string]: unknown;
}


export interface SetVolumeParams {
  volume: number;
  [key: string]: unknown;
}


export interface AddEffectParams {
  effectDto: EffectDto;
  [key: string]: unknown;
}


export interface RemoveEffectParams {
  effectId: number;
  [key: string]: unknown;
}


export interface ApplyEffectOrderChangeParams {
  effects: EffectDto[];
  [key: string]: unknown;
}


export interface ToggleEffectParams {
  effectId: number;
  [key: string]: unknown;
}


export interface SetHcDistortionThresholdParams {
  effectId: number;
  threshold: number;
  [key: string]: unknown;
}


export interface SetHcDistortionLevelParams {
  effectId: number;
  level: number;
  [key: string]: unknown;
}


export interface SetDelayLevelParams {
  effectId: number;
  level: number;
  [key: string]: unknown;
}


export interface SetDelayDelayTimeParams {
  effectId: number;
  delayTime: number;
  [key: string]: unknown;
}







