// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data Transfer Object for the placeholder cabinet effect.
 */
export type CabinetDto = { 
/**
 * Unique identifier for this effect instance.
 */
id: number, 
/**
 * Human-readable name displayed in the UI.
 */
name: string, 
/**
 * Whether the effect is currently active or bypassed.
 */
is_active: boolean, 
/**
 * UI color for the pedal chassis. Hex string format: `"#rrggbb"`.
 */
color: string, 
/**
 * IR file name loaded from `resources/default_ir`.
 */
ir_file_path: string, };
