// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DelayDto = { 
/**
 * Unique identifier for this effect instance. Used for targeting commands.
 */
id: number, 
/**
 * Human-readable name displayed in the UI pedal. Example: `"Distortion"`.
 */
name: string, 
/**
 * Whether the effect is currently active/processing audio (`true`) or bypassed (`false`).
 * When `false`, the input signal passes through unchanged.
 */
is_active: boolean, 
/**
 * UI colour for the pedal chassis. Hex string format: `"#rrggbb"`.
 */
color: string, 
/**
 * Time (ms) between the original sample and the echo's
 */
delay_time: number, 
/**
 * Output level of the Echo's in `[0.0, 0.95]`.
 * - `0.0` = no audio
 * - `0.95` = almost the same volume as the dry sample
 */
level: number, };
