// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * # Data Transfer Object for HC Distortion Effect
 *
 * `HcDistortionDto` is the serialisable representation of an [`HCDistortion`] effect
 * for communication between the Rust backend and the TypeScript frontend.
 *
 * This DTO is automatically generated for TypeScript via the `ts-rs` crate
 *
 * [`HCDistortion`]: crate::services::effects::distortion::hc_distortion::HCDistortion
 */
export type HcDistortionDto = { 
/**
 * Unique identifier for this effect instance. Used for targeting commands.
 */
id: string, 
/**
 * Human-readable name displayed in the UI pedal. Example: `"Distortion"`.
 */
name: string, 
/**
 * Whether the effect is currently active/processing audio (`true`) or bypassed (`false`).
 * When `false`, the input signal passes through unchanged.
 */
is_active: boolean, 
/**
 * UI colour for the pedal chassis. Hex string format: `"#rrggbb"`.
 */
color: string, 
/**
 * Hard-clip threshold in the range `(0.0, 1.0]`.
 */
threshold: number, 
/**
 * Normalised output level boost in `[0.0, 1.0]`.
 * - `0.0` = unity gain (no boost)
 * - `1.0` = ×2.0 boost
 */
level: number, };
