// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * # Data Transfer Object for HC Distortion Effect
 *
 * `ScDistortionDto` is the serialisable representation of an [`SCDistortion`] effect
 * for communication between the Rust backend and the TypeScript frontend.
 *
 * This DTO is automatically generated for TypeScript via the `ts-rs` crate
 *
 * [`SCDistortion`]: crate::services::effects::distortion::sc_distortion::SCDistortion
 */
export type ScDistortionDto = { 
/**
 * Unique identifier for this effect instance. Used for targeting commands.
 */
id: number, 
/**
 * Human-readable name displayed in the UI pedal. Example: `"Distortion"`.
 */
name: string, 
/**
 * Whether the effect is currently active/processing audio (`true`) or bypassed (`false`).
 * When `false`, the input signal passes through unchanged.
 */
is_active: boolean, 
/**
 * UI colour for the pedal chassis. Hex string format: `"#rrggbb"`.
 */
color: string, 
/**
 * clipping threshold in the range `[0.0, 1.0]`.
 */
threshold: number, 
/**
 * Normalised output level boost in `[0.0, 1.0]`.
 * - `0.0` = unity gain (no boost)
 * - `1.0` = ×2.0 boost
 */
level: number, 
/**
 * The smoothing factor that determines how much the curve is curved towards the clipping threshold `[1.0,10.0]`.
 */
smoothing: number, };
