// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * # Data Transfer Object for Wah Effect
 *
 * `WahDto` is the serialisable representation of a [`Wah`] effect
 * for communication between the Rust backend and the TypeScript frontend.
 *
 * This DTO is automatically generated for TypeScript via the `ts-rs` crate.
 *
 * [`Wah`]: crate::services::effects::wah::Wah
 */
export type WahDto = { 
/**
 * Unique identifier for this effect instance. Used for targeting commands.
 */
id: string, 
/**
 * Human-readable name displayed in the UI pedal. Example: `"Wah"`.
 */
name: string, 
/**
 * Whether the effect is currently active/processing audio (`true`) or bypassed (`false`).
 * When `false`, the input signal passes through unchanged.
 */
is_active: boolean, 
/**
 * UI color for the pedal chassis. Hex string format: `"#rrggbb"`.
 */
color: string, 
/**
 * Pedal expression value in `[0.0, 1.0]`.
 * - `0.0` = Heel down (Muffled/Bass)
 * - `1.0` = Toe down (Bright/Treble)
 */
pedal_position: number, };
